export  const SET_TODO:string = 'SET_TODO'
export  const SET_TODO_LIST:string = 'SET_TODO_LIST'
export  const REMOVE_TODO  = 'REMOVE_TODO'
export const SET_STATUS = 'SET_STATUS'
export const SET_DOING = 'SET_DOING'